(library
  (scaffold catalog)
  (export
    field
    field?
    field/name
    field/value
    object
    arr
    list->arr
    vector/map
    vector/append
    arr/append-list
    arr/prepend-list
    object/has-field?
    object/ref
    object/remove-fields
    object/replace-fields
    object/merge
    object/inherit
    object/override
    object/replace-field
    object/update-field
    object/map-vector-field
    object/append-field-vector
    object/append-vector
    split-fields
    call-with-split-fields
    doc
    doc-next
    extern-doc
    moduledoc
    typedoc
    signature
    summary
    markdown
    example
    param
    returns
    group
    see
    effect
    requires-capability
    stability
    since
    deprecated
    hidden
    catalog/mode
    catalog/mode?
    catalog
    catalog/from-lists
    tool-list/from-lists
    catalog/tool
    required
    required/tool
    package
    package/map-install-argvs
    build
    archive
    archive/strip-components
    dmg
    meta
    home-page
    description
    license
    maintainers
    tags
    main-program
    source
    passthru
    install/order
    depends
    install/before
    install/after
    uninstall
    uninstall/command
    host/uninstall-command
    uninstall/path
    host/uninstall-path
    tool
    tool/inherit
    tool/override
    tool/map-package-install-argvs
    tool/map-check-argvs
    uninstall/map-command-argvs
    tool/map-uninstall-command-argvs
    tool/append-bins
    install-argv/prepend
    argv/append
    tool/prefer-present
    workspace/build
    tool/bins
    tool/checks
    tool/paths
    tool/platforms
    tool/skip-verify-after-install
    host/package-platform
    host/package-platform-argvs
    uninstall/paths
    predicate
    platform/package
    check
    host/check
    bin
    bin/version
    tool/path
    package/platform
    package/platform-argvs)
  (import (rnrs) (scaffold catalog base))

  (moduledoc
    (summary
      "Public catalog-building API that re-exports core object helpers and catalog constructors.")
    (group "Catalog")))
